name: Frigate CI Test Suite

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.1', '8.2', '8.3' ]
    name: PHP ${{ matrix.php-versions }} Test
    steps:
    
    - uses: actions/checkout@v4
    - name: PHP Install
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: intl, redis, pcntl
        tools: composer:v2
      env:
        fail-fast: true
      
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-versions }}-
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction --no-ansi

    - name: Using PHP version
      run: php -v

    - name: Run test suite
      run: composer run-script test

    # - name: Coding Standards
    #   run: composer run-script phpcs